# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fb4336d6ecfc876750c1dcedd7e6d068cb75e994186c63cfbe2c8b251b1b08e876187e9cdda9f6e4e6a82ae72f5053f7847487b3749d5d3b4f4e5b89e4341f1

test:
  secret_key_base: ce241ded558eb11b00098997fc917e6d1f88ebe08ab0357df73ad07eed94447242ea091c0ea8bf365f8fbeb9aed6f0f60d01306b72aa0bead5175cc5edc4dc66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
